version: '3.8'

services:
  clip-embedder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8000"
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - DEVICE=${DEVICE}
    env_file:
      - .env
    volumes:
      - ./app:/app
