services:
  image-vector-embed:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - DEVICE=${DEVICE}
    env_file:
      - .env
    volumes:
      - ./app:/app
