services:
  image-vector-embed:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8787}:${PORT:-8787}"
    env_file:
      - .env
    volumes:
      - ./app:/app
