#!/bin/bash

set -e
source ./shared/colors

echo -e "${BOLD}${GREEN}👋 Setting up the environment...${NC}"
echo -e "${BOLD}${YELLOW}📦 Installing dependencies...${NC}"
#Ask for the port
read -p "Enter the port number (default: 8787): " PORT
PORT=${PORT:-8787}

# Only copy .env.example if .env doesn't exist
if [ ! -f .env ]; then
    echo -e "${BOLD}${YELLOW}📦 Copying .env.example to .env...${NC}"
    cp .env.example .env
fi

# Update .env with the port
sed -i "s/PORT=.*/PORT=${PORT}/" .env

# Generate key and update .env
source ./keygen