#!/bin/bash

set -e
source ./utils/colors

echo -e "${BOLD}${GREEN}👋 Setting up the environment...${NC}"
echo -e "${BOLD}${YELLOW}📦 Installing dependencies...${NC}"
PORT=${$1:-8787}

# Only copy .env.example if .env doesn't exist
if [ ! -f .env ]; then
    echo -e "${BOLD}${YELLOW}📦 Copying .env.example to .env...${NC}"
    cp .env.example .env
fi

# Update .env with the port
sed -i "s/PORT=.*/PORT=${PORT}/" .env

# Generate key and update .env
source ./keygen
echo -e "\n${BLUE}----------------------------------------${NC}\n"
echo -e "${GREEN}✓ You can now start the docker container with: ${BOLD}${YELLOW}docker-compose up -d${NC}"
